//
// Created by Petri on 27.11.2025.
//

#ifndef AIS4104_PORTFOLIO_CUBICPTPTRAJECTORYGENERATOR_H
#define AIS4104_PORTFOLIO_CUBICPTPTRAJECTORYGENERATOR_H

namespace AIS4104 {
    class CubicPTPTrajectoryGenerator {
    };
} // AIS4104

#endif //AIS4104_PORTFOLIO_CUBICPTPTRAJECTORYGENERATOR_H